import type { SessionMessage } from '../core/types.js';
import { pickLocale, type UiLocale } from '../cli/locale.js';
import type {
  ChatProvider,
  ProviderConfig,
  ProviderRequestOptions,
  ProviderResponse,
} from './types.js';

function cleanProviderBody(body: string): string {
  return body.trim();
}

function buildProviderErrorMessage(
  response: Response,
  body: string,
  config: ProviderConfig,
  locale: UiLocale = 'en',
): string {
  const lines = [
    pickLocale(locale, {
      zh: `连接测试没有通过：${response.status} ${response.statusText}`,
      en: `Connection test failed: ${response.status} ${response.statusText}`,
    }),
  ];

  const trimmedBody = cleanProviderBody(body);
  if (trimmedBody) {
    lines.push(pickLocale(locale, {
      zh: `服务端提示：${trimmedBody}`,
      en: `Server message: ${trimmedBody}`,
    }));
  }

  if (response.status === 404) {
    lines.push(pickLocale(locale, {
      zh: `没有找到对应的 Messages 接口。请确认 Base URL 是该服务的根地址；Artemis 会自动在后面加上 /v1/messages。当前 Base URL：${config.baseUrl}`,
      en: `The Messages endpoint was not found. Make sure the Base URL is the provider root; Artemis adds /v1/messages automatically. Current Base URL: ${config.baseUrl}`,
    }));
  }

  if (response.status === 401 || response.status === 403) {
    lines.push(pickLocale(locale, {
      zh: 'API key 没有通过校验。请确认 key 没有输错，并且当前账号有权限使用所选模型。',
      en: 'The API key was rejected. Check that the key is correct and that your account can use the selected model.',
    }));
  }

  if (response.status === 400) {
    lines.push(pickLocale(locale, {
      zh: `请求格式没有被服务接受。请确认模型 ${config.model} 适用于当前 Messages 接口：${config.baseUrl}`,
      en: `The service did not accept the request format. Make sure model ${config.model} works with this Messages endpoint: ${config.baseUrl}`,
    }));
  }

  return lines.join('\n');
}

function buildProviderTransportErrorMessage(
  error: unknown,
  config: ProviderConfig,
  locale: UiLocale = 'en',
): string {
  const message = error instanceof Error ? error.message : String(error);
  return [
    pickLocale(locale, {
      zh: `还没有收到服务响应，连接就中断了：${message}`,
      en: `The connection stopped before the service returned a response: ${message}`,
    }),
    pickLocale(locale, {
      zh: `当前 Base URL：${config.baseUrl}`,
      en: `Current Base URL: ${config.baseUrl}`,
    }),
    pickLocale(locale, {
      zh: `当前模型：${config.model}`,
      en: `Current model: ${config.model}`,
    }),
    pickLocale(locale, {
      zh: '请检查 Base URL、网络连接，以及代理或网关设置。',
      en: 'Check the Base URL, network connection, and any proxy or gateway settings.',
    }),
  ].join('\n');
}

type AnthropicMessageContent = string | Array<{ type: string; [key: string]: unknown }>;

function mapMessage(message: SessionMessage): { role: 'user' | 'assistant'; content: AnthropicMessageContent } {
  // Tool result → Anthropic tool_result content block
  if (message.role === 'tool' && message.toolUseId) {
    return {
      role: 'user',
      content: [{ type: 'tool_result', tool_use_id: message.toolUseId, content: message.content ?? '' }],
    };
  }
  if (message.role === 'tool') {
    // Fallback: plain user message
    return { role: 'user', content: `[tool:${message.name ?? 'unknown'}]\n${message.content}` };
  }
  // Assistant with raw content blocks from a previous Anthropic response —
  // pass them back unmodified. REQUIRED for extended thinking + tool_use
  // loops: thinking blocks carry signatures that Anthropic verifies, and the
  // spec mandates "the entire sequence of consecutive thinking blocks must
  // match the outputs generated by the model during the original request;
  // you can't rearrange or modify the sequence".
  if (message.role === 'assistant' && message.rawContentBlocks?.length) {
    return { role: 'assistant', content: message.rawContentBlocks as AnthropicMessageContent };
  }
  // Assistant with OpenAI-style toolCalls → convert to Anthropic tool_use blocks
  if (message.role === 'assistant' && message.toolCalls?.length) {
    const blocks: Array<{ type: string; [key: string]: unknown }> = [];
    if (message.content) {
      blocks.push({ type: 'text', text: message.content });
    }
    for (const tc of message.toolCalls) {
      let input: unknown = {};
      try { input = JSON.parse(tc.arguments); } catch { input = {}; }
      blocks.push({ type: 'tool_use', id: tc.id, name: tc.name, input });
    }
    return { role: 'assistant', content: blocks };
  }
  if (message.role === 'assistant') {
    return { role: 'assistant', content: message.content };
  }
  return { role: 'user', content: message.content };
}

function injectImagesIntoMessages(
  mapped: Array<{ role: 'user' | 'assistant'; content: AnthropicMessageContent }>,
  attachments: import('./types.ts').ImageAttachment[],
): void {
  let lastUserIdx = -1;
  for (let i = mapped.length - 1; i >= 0; i -= 1) {
    if (mapped[i]!.role === 'user') {
      lastUserIdx = i;
      break;
    }
  }
  if (lastUserIdx < 0 || attachments.length === 0) return;

  const existingText = mapped[lastUserIdx]!.content;
  const textStr = typeof existingText === 'string' ? existingText : '';
  const imageBlocks = attachments.map((img) => ({
    type: 'image',
    source: { type: 'base64', media_type: img.mediaType, data: img.data },
    ...(img.label ? { _label: img.label } : {}),
  }));
  mapped[lastUserIdx] = {
    role: 'user',
    content: [...imageBlocks, { type: 'text', text: textStr }],
  };
}

function extractText(
  content: Array<{ type?: string; text?: string }> | undefined,
): string {
  if (!Array.isArray(content)) {
    return '';
  }

  return content
    .map((entry) => (entry?.type === 'text' && typeof entry.text === 'string' ? entry.text : ''))
    .filter(Boolean)
    .join('\n');
}

export class MessagesCompatibleProvider implements ChatProvider {
  readonly supportsImages = true;
  readonly supportsNativeToolCalls = true;
  private readonly config: ProviderConfig;

  constructor(config: ProviderConfig) {
    this.config = config;
  }

  async complete(
    messages: SessionMessage[],
    options?: ProviderRequestOptions,
  ): Promise<ProviderResponse> {
    const startedAt = Date.now();
    const system = messages
      .filter((message) => message.role === 'system')
      .map((message) => message.content.trim())
      .filter(Boolean)
      .join('\n\n');
    const messagesApiMessages = messages
      .filter((message) => message.role !== 'system')
      .map(mapMessage);

    if (options?.imageAttachments?.length) {
      injectImagesIntoMessages(messagesApiMessages, options.imageAttachments);
    }

    // Build tools in Anthropic Messages API format (input_schema, not parameters)
    const anthropicTools = options?.nativeFunctionTools?.map((t) => ({
      name: t.name,
      description: t.description ?? '',
      input_schema: t.parameters,
    }));
    // Prompt caching: mark the last tool definition so Anthropic caches the
    // entire stable tools prefix. Saves ~90% on tool-definition input tokens
    // for subsequent requests in the same server-side session.
    if (anthropicTools?.length) {
      const last = anthropicTools[anthropicTools.length - 1]!;
      (last as Record<string, unknown>).cache_control = { type: 'ephemeral' };
    }

    // Prompt caching: send system prompt as content blocks with cache_control
    // so Anthropic caches the stable prefix. On cache hit, input_tokens for
    // the system prompt drop to ~1/10 of the full price.
    const systemBlocks = system
      ? [{ type: 'text', text: system, cache_control: { type: 'ephemeral' } }]
      : undefined;

    let response: Response;
    try {
      response = await fetch(
        `${this.config.baseUrl.replace(/\/$/, '')}/v1/messages`,
        {
          method: 'POST',
          headers: {
            'content-type': 'application/json',
            'x-api-key': this.config.apiKey,
            'anthropic-version': '2023-06-01',
          },
          body: JSON.stringify({
            model: this.config.model,
            max_tokens: 8096,
            ...(systemBlocks ? { system: systemBlocks } : {}),
            messages: messagesApiMessages,
            ...(anthropicTools?.length ? { tools: anthropicTools } : {}),
          }),
          signal: options?.abortSignal,
        },
      );
    } catch (error) {
      if (options?.abortSignal?.aborted) {
        throw error;
      }
      throw new Error(buildProviderTransportErrorMessage(error, this.config, options?.locale));
    }

    if (!response.ok) {
      const body = await response.text();
      throw new Error(buildProviderErrorMessage(response, body, this.config, options?.locale));
    }

    type AnthropicContentBlock = { type?: string; text?: string; id?: string; name?: string; input?: unknown };
    const json = (await response.json()) as {
      model?: string;
      usage?: {
        input_tokens?: number;
        output_tokens?: number;
      };
      content?: AnthropicContentBlock[];
    };

    const text = extractText(json.content);

    // Parse tool_use blocks from the response
    const toolUseBlocks = (json.content ?? []).filter((b) => b.type === 'tool_use');
    const nativeToolCalls = toolUseBlocks.length
      ? toolUseBlocks.map((b) => ({
          name: b.name ?? '',
          arguments: JSON.stringify(b.input ?? {}),
          callId: b.id ?? '',
        }))
      : undefined;

    if (!text && !nativeToolCalls?.length) {
      throw new Error('Provider returned an empty completion payload.');
    }

    const promptTokens = json.usage?.input_tokens;
    const completionTokens = json.usage?.output_tokens;

    // Capture raw content blocks for round-trip (extended thinking signatures,
    // unknown future block types). Caller stores these on the assistant
    // SessionMessage so mapMessage() can replay them verbatim next turn.
    const rawContentBlocks = Array.isArray(json.content) && json.content.length > 0
      ? json.content as any[]
      : undefined;

    return {
      text,
      raw: json,
      model: typeof json.model === 'string' ? json.model : this.config.model,
      nativeToolCalls,
      rawContentBlocks,
      usage: {
        promptTokens,
        completionTokens,
        totalTokens:
          typeof promptTokens === 'number' && typeof completionTokens === 'number'
            ? promptTokens + completionTokens
            : undefined,
        durationMs: Math.max(Date.now() - startedAt, 0),
        firstResponseMs: Math.max(Date.now() - startedAt, 0),
      },
    };
  }
}
