export function buildWorkflowStrengthContract(): string {
  return [
    'Workflow strength contract:',
    '- Treat every named workflow as a real specialist system, not a thin wrapper around one generic assistant.',
    '- Treat repository-local instructions, docs, tests, schemas, and existing code as the system of record. Keep the injected guidance short; load deeper docs only when the task needs them.',
    '- Build a task harness before claiming completion: identify the relevant static checks, focused tests, runtime smoke paths, logs/metrics, or visual evidence that would actually detect failure.',
    '- Specialist phases must add distinct value: discovery, design, architecture, assets, implementation, criticism, and verification should not collapse into the same generic summary when the task needs them.',
    '- Derive subtask, asset, keyword, and verification plans from the current user request and repo evidence. Do not hard-code catalog items, visual categories, filenames, or product concepts unless the user specifically asked for them.',
    '- Use deterministic controls where available: existing scripts, test commands, lint rules, permission limits, read-only review, and architecture checks beat advisory prose.',
    '- Do not invent products, metrics, command names, install URLs, versions, social links, or company facts. If the repository/user did not provide them, label them as placeholders, omit them, or ask for the missing source of truth.',
    '- If the user asks for generated/searched visual assets, first create a task-specific asset manifest, then produce or fetch real raster assets, then verify those files exist and are referenced.',
    '- Visual asset routing rule: classify each required asset as either photographic (camera-captured subjects — people, products, food, places, lifestyle, editorial, hero shots, lookbooks) or vector-native (icons, logos, UI affordances, loaders, abstract geometric decoration, charts, diagrams, gradients, patterns, design tokens). Photographic assets must come from generate_image (when configured) or web-search. Vector-native assets may be authored as SVG/CSS/canvas — that is the right tool for them and is not a violation. The forbidden pattern is substituting hand-authored SVG/canvas/procedural code for what is supposed to be a real photograph or product shot (e.g. writing a node/python script that draws "product images" instead of calling generate_image).',
    '- For product photography, editorial imagery, hero images, lookbooks, model shots, lifestyle scenes, or anything described with photographic terms (lens, lighting, model, pose, fabric, studio, shot, ISO, focal length), call generate_image when configured; do not silently fall back to SVG/CSS art for photographic subjects without informing the user that real generation failed.',
    '- For frontend/web/UI work, HTTP 200, file existence, and "server started" are not visual verification. Capture or otherwise inspect desktop and mobile render evidence; if browser/screenshot verification fails, report it as incomplete instead of claiming full validation.',
    '- If a tool fails, recover in the same run with a simpler concrete action or explicitly surface the blocker. Do not finish with “let me retry” or similar future-tense text after a failed action.',
    '- Verification commands must be portable and short. Assume run_command may execute under /bin/sh; avoid Bash/Zsh-only syntax such as process substitution <(...), arrays, [[ ... ]], and grep -P unless you explicitly invoke a compatible shell and keep the command simple.',
    '- run_command has a 120-second hard timeout. For any long-running process (HTTP server, file watcher, background script), use `nohup <cmd> >/tmp/<name>.log 2>&1 & echo $!` to detach AND record the PID, then immediately verify with `sleep 1 && curl -sS http://127.0.0.1:<port>/ -o /dev/null && echo SERVED` (or equivalent). Do NOT start a server without `&`; it will block until the timeout and the PID will be lost.',
    '- If a previous server start command already timed out, try a different port (the previous port may still be held by an orphaned process) and use `lsof -i :<port>` to verify before retrying the same port.',
    '- Prefer multiple simple verification commands over one fragile shell pipeline. Record the actual evidence before claiming success.',
    '- If the work exposes stale docs, dead workflow paths, or obsolete instructions, either update the local source of truth or report the exact cleanup that remains.',
  ].join('\n');
}
